In [33]:
import requests
from bs4 import BeautifulSoup as bs

In [38]:
import pandas as pd
import os
from datetime import datetime

In [39]:
# Define the URL to scrape
url = 'https://www.redfin.com/city/29470/IL/Chicago'

# Send an HTTP GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Get the HTML content of the page
    html_content = response.text
else:
    print(f"Failed to retrieve data. Status code: {response.status_code}")

In [40]:
# Parse the HTML content with BeautifulSoup
soup = bs(html_content, 'html.parser')

In [41]:
# Extract the infromation from the soup with a class
house_prices = soup.find_all('span', {"class": 'homecardV2Price'})
house_adresses = soup.find_all('span', {"class": 'collapsedAddress primaryLine'})
house_stats = soup.find_all('div', {"class": 'stats'})

In [26]:
# Create an empty dictionary to store the scraped data by extracting house 
house_obj = {
    "House_Prices": [price.text for price in house_prices],
    "House_Adress": [address.text for address in house_adresses],
    "Num_of_Beds": [house_stats[i].text for i in range(0, len(house_stats), 3)],
    "Num_of_Baths": [house_stats[i + 1].text for i in range(0, len(house_stats), 3)],
    "Square_Footage": [house_stats[i+2].text.split(" ")[0] for i in range(0, len(house_stats), 3)],
}

# Create a Pandas DataFrame from the scraped data
house_dataset = pd.DataFrame(house_obj)

# Display the resulting DataFrame
house_dataset

,House_Prices,House_Adress,Num_of_Beds,Num_of_Baths,Square_Footage
0,"$424,000","240 E Illinois St #2603, Chicago, IL 60611",1 bed,1 bath,—sq.
1,"$729,000","4339 S Oakenwald Ave, Chicago, IL 60653",4 beds,3 baths,"3,200"
2,"$3,095,000","2309 N Geneva Ter, Chicago, IL 60614",7 beds,6.5 baths,"8,000"
3,"$359,000","1850 N Clark St #2803, Chicago, IL 60614",2 beds,2 baths,"1,100"
4,"$489,000","2010 Brummel St, Evanston, IL 60202",4 beds,3 baths,"2,183"
5,"$169,000","2419 W Hollywood Ave #3, Chicago, IL 60659",2 beds,1 bath,900
6,"$215,000","1635 W Pratt Blvd Unit 3N, Chicago, IL 60626",2 beds,1 bath,850
7,"$255,000","4218 S King Dr Unit 1N, Chicago, IL 60653",3 beds,2 baths,"1,465"
8,"$384,000","757 N Orleans St #1408, Chicago, IL 60654",2 beds,1.5 baths,"1,070"
9,"$299,900","3737 N Leavitt St Unit 1N, Chicago, IL 60618",2 beds,1 bath,850
10,"$415,000","2434 N Saint Louis Ave, Chicago, IL 60647",—beds,—baths,"3,049"
11,"$730,000","3657 N Lotus Ave, Chicago, IL 60641",6 beds,3.5 baths,—sq.
12,"$199,900","3752 W 87th St, Chicago, IL 60652",3 beds,1 bath,"1,020"
13,"$2,449,900","175 E Delaware Pl #7508, Chicago, IL 60611",4 beds,4.5 baths,"4,200"
14,"$239,000","1636 W Melrose St #104, Chicago, IL 60657",1 bed,1 bath,—sq.
15,"$349,900","2405 W Flournoy St Unit B, Chicago, IL 60612",2 beds,1.5 baths,"1,500"
16,"$349,000","3338 N Paulina St Unit 2S, Chicago, IL 60657",2 beds,1 bath,—sq.
17,"$775,000","222 E Chestnut St Unit 6B, Chicago, IL 60611",3 beds,2.5 baths,"2,400"
18,"$250,000","3705 W Altgeld St #1, Chicago, IL 60647",2 beds,1 bath,—sq.
19,"$294,900","2024 S Wabash Ave #204, Chicago, IL 60616",2 beds,2 baths,"1,290"
20,"$550,000","2717 W Adams St, Chicago, IL 60612",4 beds,3 baths,"2,200"
21,"$515,000","2452 N Racine Ave Unit 3N, Chicago, IL 60614",2 beds,1 bath,"1,200"
22,"$475,000","2619 W Carmen Ave, Chicago, IL 60625",—beds,—baths,—sq.
23,"$2,750,000","130 N Garland Ct Unit 2711-12, Chicago, IL 60602",3 beds,3.5 baths,"4,350"
24,"$329,900","7727 S Karlov Ave, Chicago, IL 60652",4 beds,2.5 baths,"1,900"
25,"$150,000","1528 W Fargo Ave Unit GN, Chicago, IL 60626",1 bed,1 bath,700
26,"$389,900","2932 N Parkside Ave, Chicago, IL 60634",5 beds,2 baths,—sq.
27,"$19,900","4216 S Calumet Ave, Chicago, IL 60653",—beds,—baths,"2,178"
28,"$345,000","175 E Delaware Pl #5014, Chicago, IL 60611",1 bed,1 bath,948
29,"$125,000","1212 W 109th Pl, Chicago, IL 60643",2 beds,1 bath,"1,360"
30,"$384,000","2307 W Roscoe St #1, Chicago, IL 60618",2 beds,2 baths,"1,200"
31,"$159,900","2060 W Chase Ave Unit 1C, Chicago, IL 60645",2 beds,1.5 baths,"1,045"
32,"$175,000","2142 W Rosemont Ave Unit 3D, Chicago, IL 60659",2 beds,1 bath,"1,100"
33,"$1,125,000","2104 S Washtenaw Ave, Chicago, IL 60608",15 beds,8 baths,—sq.
34,"$85,000","5217 S Green St, Chicago, IL 60609",6 beds,3.5 baths,"1,127"
35,"$234,900","6260 S Newland Ave Unit 1N, Chicago, IL 60638",2 beds,1.5 baths,"1,000"
36,"$149,000","7028 S Sangamon St, Chicago, IL 60621",6 beds,2 baths,—sq.
37,"$1,095,000","3958 S Drexel Blvd, Chicago, IL 60653",5 beds,4.5 baths,"4,000"
38,"$800,000","2024 W Irving Park Rd #304, Chicago, IL 60618",3 beds,2.5 baths,—sq.
39,"$725,000","2024 W Irving Park Rd #203, Chicago, IL 60618",3 beds,2.5 baths,—sq.

In [42]:
import pandas as pd
import os
from datetime import datetime

# Define the path to the 'data' folder within your project directory
data_folder = "../data"

# Ensure the 'data' folder exists; if not, create it
if not os.path.exists(data_folder):
    os.makedirs(data_folder)

# Generate a timestamp for the filename
timestamp = datetime.now().strftime("%Y.%m.%d")

# Create a unique filename for the CSV file in the 'data' folder using the timestamp
csv_filename = os.path.join(data_folder, f"home_data_{timestamp}.csv")

# Save the DataFrame to the CSV file
house_dataset.to_csv(csv_filename, index=False)

# Print the generated filename
print(f"Data saved to {csv_filename}")

Data saved to ../data\home_data_2023.10.05.csv